
filebeat.modules:
  - module: suricata
    eve:
      enabled: true
      var.paths: ["/var/log/suricata/eve.json"]
      var.index: "honeyplc"
      

# Template setup for honeyplc
setup.template.name: "honeyplc"
setup.template.pattern: "honeyplc-*"


# Elasticsearch output configuration
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  indices:
    - index: "honeyplc"
      when.equals:
        event.dataset: "suricata.eve"

        